### PR TITLE
curriculum: add curriculums for UG stuff

### PR DESCRIPTION
**Pull request by abhiramtilakiiit**
## Changes

- Rename all the inital files.
- Add a common route for curriculms to get the list.

## Linked PRs

- In Frontend repo: https://github.com/IMS-IIITH/frontend/pull/165

### CODE REVIEW

**Comment by bhavberi** [comment]
@abhiramtilakiiit Try to keep simpler names from the backend side, such as `CSE.pdf`, `CSD.pdf` and so on. Long names are things of UI, and not backend. Backend needs to be as simple and straightforward as possible

**Comment by abhiramtilakiiit** [comment]
> 

> @abhiramtilakiiit Try to keep simpler names from the backend side, such as `CSE.pdf`, `CSD.pdf` and so on. Long names are things of UI, and not backend. Backend needs to be as simple and straightforward as possible

 I don't want to store stuff in frontend and Only  the filename should be able to giveoff all info like in almanacs

**Comment by bhavberi** [comment]
Ok, cool, let's go with this one for now. 

Remove the 1,2,3,4s from the names of the files, as they are not ordered in practical sense.
And then merge this PR

**Review by bhavberi — CHANGES_REQUESTED** [review]
Remove the 1,2,3,4s from the names of the files, as the curriculumns are not ordered in practical sense.

**Review by bhavberi — APPROVED** [review]

**Comment by bhavberi** [comment]
Based on our discussion, merging this PR.

**Pull request merged**
